name: Validate Renovate configuration

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.head_ref }}
  cancel-in-progress: true

env:
  # renovate: datasource=npm depName=renovate
  RENOVATE_VERSION: "43.64.3"

jobs:
  validate-renovate-config:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0
        with:
          version: "10.32.1"
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: "24.14.0"
      # Avoid installing packages that are newer than 1 week old to reduce supply chain attacks probability.
      - run: pnpm config set minimumReleaseAge 10080
      - run: pnpm --package renovate@${{ env.RENOVATE_VERSION }} dlx renovate-config-validator default.json5 renovate.json5
