name: Validate Renovate configuration

on:
  pull_request:
    paths-ignore:
      - .github/workflows/validate-renovate-config.yml
      - default.json5
      - renovate.json5

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.head_ref }}
  cancel-in-progress: true

jobs:
  validate-renovate-config:
    runs-on: ubuntu-22.04
    steps:
      - run: echo 'Modified files do not require a run, skipping the job.'
