name: Validate Renovate configuration

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.head_ref }}
  cancel-in-progress: true

env:
  # renovate: datasource=npm depName=renovate
  RENOVATE_VERSION: "43.265.3"

jobs:
  validate-renovate-config:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          version: "11.13.1"
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "24.18.0"
      # Avoid installing packages that are newer than 1 week old to reduce supply chain attacks probability.
      - run: pnpm config set minimumReleaseAge 10080
      - run: pnpm --package renovate@${{ env.RENOVATE_VERSION }} dlx renovate-config-validator default.json5 renovate.json5
